name: CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: "true"

      - uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Install dependencies
        run: just install

      - name: CI
        run: DEBUG=@grampelberg/spotcheck:* just ci

      - name: debug
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: __debug__
