name: CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Install dependencies
        run: just install

      - name: CI
        run: just ci

      - name: Run tests
        run: DEBUG=@grampelberg/spotcheck:* bun test
